title: Bob Tillman
description: Slate is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
url: https://davepum.github.io # the base hostname & protocol for your site
